/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1xeuzRbA6sP
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

"use client";

import Link from "next/link";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import Image from "next/image";
import { motion } from "framer-motion";
import Carousel from "./carousel/carousel";
import { bakeMenu, blogMenu, gallery } from "./bakeMenu";
import { CircleIndicator } from "@/components/scroll-animation/scroll";

export default function homeComponent() {
  return (
    <>
  <Carousel />
    <div className="md:flex-1">
      <CircleIndicator />
      <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
        <div className="container grid gap-12 px-4 md:px-6">
          <div className="space-y-4 text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Our Delicious Offerings
            </h2>
            <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              Explore our selection of freshly baked goods, each crafted with
              love and attention to detail.
            </p>
          </div>
          <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
            {bakeMenu.map((menu) => (
              <motion.div
              whileHover={{
                scale: 1.1,
                transition: { duration: 1 },
              }}
                key={menu.id}
                className="relative overflow-hidden rounded-lg shadow-lg group hover:shadow-xl hover:-translate-y-2 hover:bg-gradient-to-r from-primary to-secondary"
              >
                <Link
                  href="#"
                  className="absolute inset-0 z-10"
                  prefetch={false}
                >
                  <span className="sr-only">View</span>
                </Link>
                <Image
                  src={menu.image ?? "/placeholder.png"}
                  alt="Croissant"
                  width={500}
                  height={400}
                  className="object-cover w-full h-64 rounded-t hover:shadow-2xl"
                />
                <div className="p-4 bg-background">
                  <h3 className="text-xl font-bold">{menu.title}</h3>
                  <p className="text-muted-foreground">{menu.context}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container grid items-center gap-8 px-4 md:px-6 lg:grid-cols-2 lg:gap-16">
          <div className="space-y-4">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              About Our Baking Journey
            </h2>
            <p className="text-muted-foreground md:text-xl">
              Baking has always been a passion of mine, ever since I was a child
              helping my grandmother in the kitchen. I&lsquo;ve honed my skills
              over the years, experimenting with different techniques and
              ingredients to create the perfect baked goods. My mission is to
              share the joy of baking with everyone who steps into our bakery.
            </p>
            <Link
              href="#"
              className="inline-flex h-9 items-center justify-center rounded bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}
            >
              Learn More
            </Link>
          </div>
          <motion.div
            animate={{
              scale: [0.5, 1, 1, 0.5, 1],
              rotate: [0, 0, 270, 270, 0],
              borderRadius: ["20%", "20%", "50%", "50%", "20%"],
            }}
          >
            <Image
              src="https://ik.imagekit.io/munchery/blog/tr:w-768/how-to-master-basics-of-baking-at-home.jpeg"
              width={600}
              height={600}
              alt="Baker's Story"
              className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center sm:w-full"
            />
          </motion.div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
        <div className="container grid items-center gap-8 px-4 md:px-6 lg:grid-cols-2 lg:gap-16">
          <div className="grid gap-6">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Gallery of Our Creations
            </h2>
            <div className="grid grid-cols-2 gap-4">
              {gallery.map((item) => (
                <Image
                  key={item.id}
                  src={item.image ?? "/placeholder.png"}
                  alt={item.title ?? "a photo of a cake"}
                  width={300}
                  height={300}
                  className="rounded-lg object-cover"
                />
              ))}
            </div>
            <Link
              href="#"
              className="inline-flex h-9 items-center justify-center rounded bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}
            >
              View Gallery
            </Link>
          </div>
          <Image
            src="/home/products/rice-two.jpeg"
            width={600}
            height={600}
            alt="Gallery Hero"
            className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center sm:w-full"
          />
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container grid gap-12 px-4 md:px-6">
          <div className="space-y-4 text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl text-secondary-foreground/50 hover:text-secondary-foreground">
              From Our Baking Blog
            </h2>
            <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              Explore our latest blog posts for insights into the art of baking.
            </p>
          </div>
          <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
            {blogMenu.map((post) => (
              <motion.article
              whileHover={{
                scale: 1.1,
                transition: { duration: 1 },
              }}
                key={post.id}
                className="relative overflow-hidden rounded-lg shadow-lg group hover:shadow-xl hover:-translate-y-2 hover:bg-gradient-to-r from-primary to-secondary"
              >
                <Link
                  href={post.path ?? "#"}
                  className="absolute inset-0 z-10"
                  prefetch={false}
                >
                  <span className="sr-only">Read Post</span>
                </Link>
                <Image
                  src={post.image ?? "/placeholder.png"}
                  alt={post.title ?? "This is something baked though"}
                  width={500}
                  height={400}
                  className="object-cover w-full h-64 rounded-t hover:shadow-2xl"
                />
                <div className="p-4 bg-background">
                  <h3 className="text-xl font-bold">{post.title}</h3>
                  <p className="text-muted-foreground">{post.context}</p>
                </div>
              </motion.article>
            ))}
          </div>
          <div className="flex justify-center">
            <Link
              href="#"
              className="inline-flex h-9 items-center justify-center rounded bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}
            >
              View All Posts
            </Link>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
        <div className="container grid items-center gap-8 px-4 md:px-6 lg:grid-cols-2 lg:gap-16">
          <div className="space-y-4">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Get in Touch
            </h2>
            <p className="text-muted-foreground md:text-xl">
              Have a question or want to place an order? Fill out the form below
              and we&lsquo;ll get back to you as soon as possible.
            </p>
            <div className="w-60 h-64">
              <Link href={'https://us17.list-manage.com/contact-form?u=dda813d4daaac1a00645e1d28&form_id=fcf0e1c7f9ca5ee62d35fbc822b77378'}>
              <Button className="bg-primary/30 rounded">
              Contact Us
              </Button>
              </Link>
            </div>
          </div>
          <Image
            src="https://lyndells.com/wp-content/themes/lyndells-wptheme%20v1.0/img/banner-contact-500x340.jpg"
            width={600}
            height={600}
            alt="Contact"
            className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center sm:w-full"
          />
        </div>
      </section>
    </div>
    </>
  );
}
